params:
  seed: ${...seed}
  algo:
    name: sac

  model:
    name: soft_actor_critic

  network:
    name: soft_actor_critic
    separate: True

    space:
      continuous:
#        mu_activation: None
#        sigma_activation: None
#        mu_init:
#          name: default
#        sigma_init:
#          name: const_initializer
#          val: 0
        fixed_sigma: False
    mlp:
      units: [256, 128, 64]
      activation: relu
#      d2rl: False

      initializer:
        name: default
#      regularizer:
#        name: None
    log_std_bounds: [-5, 2]   # default

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:FrankaCabinetSAC,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    multi_gpu: False
    normalize_input: True
    reward_shaper: # needed
      scale_value: 1.0
    device: ${....rl_device}   # sac_device

    max_epochs: 10000
    num_steps_per_episode: 500
    save_best_after: 100
    save_frequency: 10000
    gamma: 0.99
    init_alpha: 1   # inital log_alpha
    actor_lr: 0.0005    # policy lr, can set actor(/critic/alpha)_betas ,default=[0.9,0.999]
    critic_lr: 0.0005   # qf lr
    critic_tau: 0.005   # critic soft update tau
    alpha_lr: 0.005    # sac entropy tuning alpha
    batch_size: 1024
    learnable_temperature: True   # learnable alpha, alpha_lr
    num_seed_steps: 5 # first few epochs, random play
    replay_buffer_size: 1000000



    mixed_precision: True
    normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.numEnvs}
#    normalize_advantage: True
#    tau: 0.95
#    learning_rate: 5e-4
#    lr_schedule: adaptive
#    kl_threshold: 0.008
#    score_to_win: 10000000
#    print_stats: True
#    grad_norm: 1.0
#    entropy_coef: 0.0
#    truncate_grads: True
#    e_clip: 0.2
#    horizon_length: 1000
#    minibatch_size: 2048
##    minibatch_size: 10
#    mini_epochs: 8
#    critic_coef: 4
#    clip_value: True
#    seq_len: 4
#    bounds_loss_coef: 0.0001
